package com.mycompany.abmc.biblioteca.forms;

import com.mycompany.abmc.biblioteca.DBConnection;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class BookDetailsForm extends javax.swing.JFrame {

    DBConnection db = null;
    int id;

    final void loadBooks() {
        String query = "SELECT * FROM libro WHERE id = ?";

        db = new DBConnection();
        db.open();

        try {
            PreparedStatement statement = db.connection.prepareStatement(query);
            statement.setInt(1, id);
            System.out.println(statement);
            ResultSet result = statement.executeQuery();
            result.next();

            String name = result.getString("nombre");
            String author = result.getString("autor");
            String description = result.getString("descripcion");

            Title.setText(name);
            FieldName.setText(name);
            FieldAuthor.setText(author);
            FieldDescription.setText(description);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * Creates new form BooksForm
     *
     * @param id Book's id
     */
    public BookDetailsForm(int id) {
        initComponents();
        this.id = id;
        loadBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        FieldAuthor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ButtonEdit = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();
        FieldDescription = new javax.swing.JTextField();
        DescriptionLabel = new javax.swing.JLabel();
        ButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir nuevo libro");
        setResizable(false);
        setSize(new java.awt.Dimension(376, 131));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(8, 8, 8));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Title.setText("Título del libro");

        FieldName.setEditable(false);
        FieldName.setBackground(new java.awt.Color(255, 255, 255));
        FieldName.setForeground(new java.awt.Color(8, 8, 8));
        FieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNameKeyPressed(evt);
            }
        });

        jLabel1.setText("Nombre");

        FieldAuthor.setEditable(false);
        FieldAuthor.setBackground(new java.awt.Color(255, 255, 255));
        FieldAuthor.setForeground(new java.awt.Color(8, 8, 8));
        FieldAuthor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldAuthorKeyPressed(evt);
            }
        });

        jLabel2.setText("Autor");

        ButtonEdit.setForeground(new java.awt.Color(8, 8, 8));
        ButtonEdit.setText("Editar");
        ButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEditMouseClicked(evt);
            }
        });

        GoBackButton.setText("Volver");
        GoBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonMouseClicked(evt);
            }
        });

        FieldDescription.setEditable(false);
        FieldDescription.setBackground(new java.awt.Color(255, 255, 255));
        FieldDescription.setForeground(new java.awt.Color(8, 8, 8));
        FieldDescription.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        FieldDescription.setMinimumSize(new java.awt.Dimension(64, 32));
        FieldDescription.setPreferredSize(new java.awt.Dimension(64, 32));
        FieldDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldDescriptionKeyPressed(evt);
            }
        });

        DescriptionLabel.setText("Descripción");

        ButtonDelete.setBackground(new java.awt.Color(204, 0, 0));
        ButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDelete.setText("Eliminar");
        ButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GoBackButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(DescriptionLabel))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(FieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(FieldDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ButtonEdit)
                        .addGap(16, 16, 16)
                        .addComponent(ButtonDelete)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(GoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(DescriptionLabel)
                .addGap(4, 4, 4)
                .addComponent(FieldDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void returnToBooksList() {
        this.dispose();
        new BooksListForm().setVisible(true);
    }

    private void GoBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonMouseClicked
        returnToBooksList();
    }//GEN-LAST:event_GoBackButtonMouseClicked

    private void ButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDeleteMouseClicked
        String query = "DELETE FROM libro WHERE id = ?";

        try {
            PreparedStatement statement = db.connection.prepareStatement(query);
            statement.setInt(1, id);
            statement.execute();
            JOptionPane.showMessageDialog(null, "Libro eliminado correctamente.");
            returnToBooksList();
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_ButtonDeleteMouseClicked

    boolean isEditable = false;

    void editingLogic() {
        if (isEditable == false) {
            isEditable = true;
            ButtonEdit.setText("Confirmar");
        } else {
            isEditable = false;

            String newName = FieldName.getText();
            String newAuthor = FieldAuthor.getText();
            String newDescription = FieldDescription.getText();

            String query = "UPDATE libro SET nombre = ?, autor = ?, descripcion = ? WHERE id = ?";

            try {
                PreparedStatement statement = db.connection.prepareStatement(query);
                statement.setString(1, newName);
                statement.setString(2, newAuthor);
                statement.setString(3, newDescription);
                statement.setInt(4, id);

                statement.execute();
                JOptionPane.showMessageDialog(null, "Libro editado correctamente.");
                Title.setText(newName);
            } catch (SQLException ex) {
                System.out.println(ex);
            }
            ButtonEdit.setText("Editar");
        }
        FieldName.setEditable(isEditable);
        FieldAuthor.setEditable(isEditable);
        FieldDescription.setEditable(isEditable);
    }

    private void ButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEditMouseClicked
        editingLogic();
    }//GEN-LAST:event_ButtonEditMouseClicked

    private void FieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNameKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && isEditable == true ) {
            editingLogic();
        }
    }//GEN-LAST:event_FieldNameKeyPressed

    private void FieldAuthorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldAuthorKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && isEditable == true ) {
            editingLogic();
        }
    }//GEN-LAST:event_FieldAuthorKeyPressed

    private void FieldDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldDescriptionKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && isEditable == true ) {
            editingLogic();
        }
    }//GEN-LAST:event_FieldDescriptionKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BookDetailsForm(9).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextField FieldAuthor;
    private javax.swing.JTextField FieldDescription;
    private javax.swing.JTextField FieldName;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
