package ui.book;

import ui.member.MembersListForm;

public class Home extends javax.swing.JFrame {

    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        OpenBooksButton = new javax.swing.JButton();
        OpenMembersButton = new javax.swing.JButton();
        Title1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Table.dropCellForeground"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        setForeground(java.awt.Color.cyan);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(8, 8, 8));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Biblioteca");

        OpenBooksButton.setBackground(new java.awt.Color(76, 0, 0));
        OpenBooksButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OpenBooksButton.setForeground(new java.awt.Color(255, 255, 255));
        OpenBooksButton.setText("Ver libros");
        OpenBooksButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OpenBooksButton.setMaximumSize(new java.awt.Dimension(79, 36));
        OpenBooksButton.setMinimumSize(new java.awt.Dimension(79, 36));
        OpenBooksButton.setPreferredSize(new java.awt.Dimension(79, 36));
        OpenBooksButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenBooksButtonMouseClicked(evt);
            }
        });

        OpenMembersButton.setBackground(new java.awt.Color(76, 0, 0));
        OpenMembersButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OpenMembersButton.setForeground(new java.awt.Color(255, 255, 255));
        OpenMembersButton.setText("Ver socios");
        OpenMembersButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        OpenMembersButton.setMaximumSize(new java.awt.Dimension(79, 36));
        OpenMembersButton.setMinimumSize(new java.awt.Dimension(79, 36));
        OpenMembersButton.setPreferredSize(new java.awt.Dimension(79, 36));
        OpenMembersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenMembersButtonMouseClicked(evt);
            }
        });

        Title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title1.setForeground(new java.awt.Color(8, 8, 8));
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("E.E.S.T. N°1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OpenMembersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OpenBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title1)
                .addGap(24, 24, 24)
                .addComponent(OpenBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OpenMembersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenBooksButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenBooksButtonMouseClicked
        new BooksListForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OpenBooksButtonMouseClicked

    private void OpenMembersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMembersButtonMouseClicked
        new MembersListForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OpenMembersButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenBooksButton;
    private javax.swing.JButton OpenMembersButton;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    // End of variables declaration//GEN-END:variables
}
