package ui.member;

import entities.Member;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import services.DBConnection;
import javax.swing.JOptionPane;
import services.MemberStore;
import services.TagStore;

public class CreateMemberForm extends javax.swing.JFrame {

    DBConnection db = new DBConnection();
        
    /**
     * Creates new form BooksForm
     */
    public CreateMemberForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Fields = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FieldDni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FieldSurname = new javax.swing.JTextField();
        Buttons = new javax.swing.JPanel();
        ButtonAdd = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir nuevo socio");
        setResizable(false);
        setSize(new java.awt.Dimension(376, 131));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Title.setForeground(new java.awt.Color(8, 8, 8));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Añadir nuevo socio");

        Fields.setLayout(new java.awt.GridLayout(6, 2));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("DNI");
        Fields.add(jLabel4);

        FieldDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldDni.setPreferredSize(new java.awt.Dimension(64, 32));
        FieldDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldDniKeyPressed(evt);
            }
        });
        Fields.add(FieldDni);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nombre");
        Fields.add(jLabel6);

        FieldName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldName.setPreferredSize(new java.awt.Dimension(64, 32));
        FieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNameKeyPressed(evt);
            }
        });
        Fields.add(FieldName);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido");
        Fields.add(jLabel5);

        FieldSurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldSurname.setPreferredSize(new java.awt.Dimension(64, 32));
        FieldSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldSurnameKeyPressed(evt);
            }
        });
        Fields.add(FieldSurname);

        Buttons.setLayout(new java.awt.GridLayout(2, 1, 16, 16));

        ButtonAdd.setBackground(new java.awt.Color(76, 0, 0));
        ButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAdd.setText("Añadir");
        ButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAddMouseClicked(evt);
            }
        });
        Buttons.add(ButtonAdd);

        GoBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GoBackButton.setText("Volver");
        GoBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackButtonMouseClicked(evt);
            }
        });
        Buttons.add(GoBackButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Title)
                .addGap(16, 16, 16)
                .addComponent(Fields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void addBook() {
        String dni = FieldDni.getText();
        String name = FieldName.getText();
        String surname = FieldSurname.getText();

        Member member = new Member(dni, name, surname);
        
        try {
            MemberStore.save(db, member);
            JOptionPane.showMessageDialog(null, "Socio añadido correctamente!");
            this.dispose();
            new MembersListForm().setVisible(true);
        } catch (HeadlessException ex) {
            System.out.println(ex);
        }
    }
    
    private void ButtonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAddMouseClicked
        addBook();
    }//GEN-LAST:event_ButtonAddMouseClicked

    private void GoBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackButtonMouseClicked
        this.dispose();
        new MembersListForm().setVisible(true);
    }//GEN-LAST:event_GoBackButtonMouseClicked

    private void FieldSurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldSurnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldSurnameKeyPressed

    private void FieldDniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldDniKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldDniKeyPressed

    private void FieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNameKeyPressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateMemberForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JPanel Buttons;
    private javax.swing.JTextField FieldDni;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldSurname;
    private javax.swing.JPanel Fields;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
